### ISSUE TITLE
libcoveocds commandline fails for record packages

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/lib-cove-ocds#39]
```bash
$ wget 'https://gist.githubusercontent.com/Bjwebb/f18545c007c31c6655eafbdcc1ff617c/raw/aa5a3e06b9baec1b8c5a2e1ffa4c86bdf3a63e66/records_invalid_releases_less_fuzzing.json'
$ libcoveocds records_invalid_releases_less_fuzzing.json 
Traceback (most recent call last):
  File "/home/bjwebb/opendataservices/open-contracting/lib-cove-ocds/.ve/bin/libcoveocds", line 11, in <module>
    load_entry_point('libcoveocds', 'console_scripts', 'libcoveocds')()
  File "/home/bjwebb/opendataservices/open-contracting/lib-cove-ocds/libcoveocds/cli/__main__.py", line 28, in main
    print(json.dumps(result, indent=4))
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'set' is not JSON serializable
```

**Comment by ghost** [comment]
I just found this with some real data: https://budeshi.ng/api/record/1288

The problem is:  result['records_aggregates']['unique_ocids'] is a set

**Comment by ghost** [comment]
I suggested a quick fix at the CLI level, but maybe we want to consider if this issue effects other places?

**Comment by jpmckinney** [comment]
I don't see any other relevant json.dump in this library (maybe relevant to other repos).
